
            # Construct initial environment
            (new Environment 'NIL '(
                (left_gripper gripping none)
                (right_gripper gripping none)
                (table identity Block)
                (M_blk1 identity Block)
                (M_blk2 identity Block)
                (M_blk3 identity Block)
                (M_blk4 identity Block)
                (M_blk5 identity Block)
                (M_blk6 identity Block)
                (M_blk7 identity Block)
                (M_blk8 identity Block)
                (U_blk1 identity Block)
                (U_blk2 identity Block)
                (U_blk3 identity Block)
                (U_blk4 identity Block)
                (U_blk5 identity Block)
            ))

            # Construct demo (list of (action . env_updates))
            # (move_object U_blk1 table true)
            ((move_arm_and_grasp right_gripper U_blk1)
                (right_gripper gripping U_blk1))
            ((move_grasped_object right_gripper table true))
            ((release right_gripper)
                (right_gripper gripping none))

            # (move_object U_blk4 U_blk1 true)
            ((move_arm_and_grasp right_gripper U_blk4)
                (right_gripper gripping U_blk4))
            ((move_grasped_object right_gripper U_blk1 true))
            ((release right_gripper)
                (right_gripper gripping none))

            # (move_object U_blk3 U_blk4 true)
            ((move_arm_and_grasp right_gripper U_blk3)
                (right_gripper gripping U_blk3))
            ((move_grasped_object right_gripper U_blk4 true))
            ((release right_gripper)
                (right_gripper gripping none))

            # (move_object U_blk2 U_blk1 true)
            ((move_arm_and_grasp right_gripper U_blk2)
                (right_gripper gripping U_blk2))
            ((move_grasped_object right_gripper U_blk1 true))
            ((release right_gripper)
                (right_gripper gripping none))

            # (move_object U_blk5 U_blk2 true)
            ((move_arm_and_grasp right_gripper U_blk5)
                (right_gripper gripping U_blk5))
            ((move_grasped_object right_gripper U_blk2 true))
            ((release right_gripper)
                (right_gripper gripping none))

            # (move_object M_blk3 table true)
            ((move_arm_and_grasp right_gripper M_blk3)
                (right_gripper gripping M_blk3))
            ((move_grasped_object right_gripper table true))
            ((release right_gripper)
                (right_gripper gripping none))

            # (move_object M_blk6 M_blk3 true)
            ((move_arm_and_grasp right_gripper M_blk6)
                (right_gripper gripping M_blk6))
            ((move_grasped_object right_gripper M_blk3 true))
            ((release right_gripper)
                (right_gripper gripping none))

            # (move_object M_blk4 table true)
            ((move_arm_and_grasp right_gripper M_blk4)
                (right_gripper gripping M_blk4))
            ((move_grasped_object right_gripper table true))
            ((release right_gripper)
                (right_gripper gripping none))

            # (move_object M_blk7 M_blk4 true)
            ((move_arm_and_grasp right_gripper M_blk7)
                (right_gripper gripping M_blk7))
            ((move_grasped_object right_gripper M_blk4 true))
            ((release right_gripper)
                (right_gripper gripping none))

            # (move_object M_blk1 M_blk6 true)
            ((move_arm_and_grasp right_gripper M_blk1)
                (right_gripper gripping M_blk1))
            ((move_grasped_object right_gripper M_blk6 true))
            ((release right_gripper)
                (right_gripper gripping none))

            # (move_object M_blk5 table true)
            ((move_arm_and_grasp right_gripper M_blk5)
                (right_gripper gripping M_blk5))
            ((move_grasped_object right_gripper table true))
            ((release right_gripper)
                (right_gripper gripping none))

            # (move_object M_blk8 M_blk5 true)
            ((move_arm_and_grasp right_gripper M_blk8)
                (right_gripper gripping M_blk8))
            ((move_grasped_object right_gripper M_blk5 true))
            ((release right_gripper)
                (right_gripper gripping none))

            # (move_object M_blk2 M_blk8 true)
            ((move_arm_and_grasp right_gripper M_blk2)
                (right_gripper gripping M_blk2))
            ((move_grasped_object right_gripper M_blk8 true))
            ((release right_gripper)
                (right_gripper gripping none))

            NIL

