
            # Construct initial environment
            (new Environment 'NIL '(
                (left_gripper gripping none)
                (right_gripper gripping none)
                (table identity Block)
                (A_blk1 identity Block)
                (A_blk2 identity Block)
                (I_blk1 identity Block)
                (I_blk2 identity Block)
                (M_blk3 identity Block)
                (M_blk4 identity Block)
                (M_blk6 identity Block)
                (U_blk3 identity Block)
                (U_blk4 identity Block)
                (U_blk5 identity Block)
            ))

            # Construct demo (list of (action . env_updates))
            # (move_object U_blk3 table true)
            ((move_arm_and_grasp right_gripper U_blk3)
                (right_gripper gripping U_blk3))
            ((move_grasped_object right_gripper table true))
            ((release right_gripper)
                (right_gripper gripping none))

            # (move_object U_blk4 table true)
            ((move_arm_and_grasp right_gripper U_blk4)
                (right_gripper gripping U_blk4))
            ((move_grasped_object right_gripper table true))
            ((release right_gripper)
                (right_gripper gripping none))

            # (move_object A_blk2 table true)
            ((move_arm_and_grasp right_gripper A_blk2)
                (right_gripper gripping A_blk2))
            ((move_grasped_object right_gripper table true))
            ((release right_gripper)
                (right_gripper gripping none))

            # (move_object M_blk6 A_blk2 false)
            ((move_arm_and_grasp right_gripper M_blk6)
                (right_gripper gripping M_blk6))
            ((move_grasped_object right_gripper A_blk2 false))
            ((release right_gripper)
                (right_gripper gripping none))

            # (move_object U_blk5 A_blk2 false)
            ((move_arm_and_grasp right_gripper U_blk5)
                (right_gripper gripping U_blk5))
            ((move_grasped_object right_gripper A_blk2 false))
            ((release right_gripper)
                (right_gripper gripping none))

            # (move_object A_blk1 A_blk2 true)
            ((move_arm_and_grasp right_gripper A_blk1)
                (right_gripper gripping A_blk1))
            ((move_grasped_object right_gripper A_blk2 true))
            ((release right_gripper)
                (right_gripper gripping none))

            # (move_object I_blk1 table true)
            ((move_arm_and_grasp right_gripper I_blk1)
                (right_gripper gripping I_blk1))
            ((move_grasped_object right_gripper table true))
            ((release right_gripper)
                (right_gripper gripping none))

            # (move_object M_blk3 I_blk1 false)
            ((move_arm_and_grasp right_gripper M_blk3)
                (right_gripper gripping M_blk3))
            ((move_grasped_object right_gripper I_blk1 false))
            ((release right_gripper)
                (right_gripper gripping none))

            # (move_object M_blk4 M_blk3 false)
            ((move_arm_and_grasp right_gripper M_blk4)
                (right_gripper gripping M_blk4))
            ((move_grasped_object right_gripper M_blk3 false))
            ((release right_gripper)
                (right_gripper gripping none))

            # (move_object I_blk2 M_blk4 false)
            ((move_arm_and_grasp right_gripper I_blk2)
                (right_gripper gripping I_blk2))
            ((move_grasped_object right_gripper M_blk4 false))
            ((release right_gripper)
                (right_gripper gripping none))

            NIL

